"""Convert a legacy game script (.ysc) for Enhanced with the table from learn_ysc.py (research/phase0.md §26).
usage: convert_ysc.py <ysc_tables.inc or map.json> check <legacy folder> <Enhanced folder>   -> how many converted scripts equal Enhanced's
       convert_ysc.py <map.json> one <legacy.ysc>                          -> what would change
       convert_ysc.py <map.json> inc <out.inc>                             -> the table for src/loader/convert/ysc.cpp

Both versions run the same bytecode with the same native hashes; only global indices move. Scripts carry the globals
signature of their build at +0x18 of the program header."""
import bisect, json, os, struct, sys
sys.path.insert(0, os.path.dirname(__file__))
from ysc import load, ptr
from learn_ysc import GLOBAL16, GLOBAL24

LEGACY_SIGNATURE, ENHANCED_SIGNATURE = 0x582CE9D8, 0xA2BE51AC


class Tables:
    def __init__(self, path):
        if path.endswith(".inc"):  # src/loader/convert/ysc_tables.inc, as tools/learn_ysc writes it
            import re
            pairs = sorted((int(a), int(b)) for a, b in re.findall(r"\{(\d+), (\d+)\}", open(path, encoding="utf-8").read()))
        else:
            pairs = sorted((int(k), v) for k, v in json.load(open(path))["global_map"].items())
        self.legacy = [a for a, _ in pairs]
        self.enhanced = [b for _, b in pairs]

    def global_index(self, g):
        """(Enhanced index, exact?) as src/loader/convert/ysc.cpp: globals the game's scripts use come from the table,
        others are moved like the known one below them (exact when the next known one moved the same)."""
        i = bisect.bisect_left(self.legacy, g)
        if i < len(self.legacy) and self.legacy[i] == g:
            return self.enhanced[i], True
        if i == 0:
            return None, False
        shift = self.enhanced[i - 1] - self.legacy[i - 1]
        exact = i < len(self.legacy) and self.enhanced[i] - self.legacy[i] == shift
        return g + shift, exact


class Script:
    """The decompressed virtual block with the program header's views (as tools/ysc.py)."""
    def __init__(self, path):
        self.x, self.vs = load(path)
        self.x = bytearray(self.x)
        q = lambda o: struct.unpack_from("<Q", self.x, o)[0]
        self.codesize = struct.unpack_from("<I", self.x, 0x1C)[0]
        cp = ptr(q(0x10), self.vs)
        self.pages = [ptr(q(cp + 8 * i), self.vs) for i in range((self.codesize + 0x3FFF) // 0x4000)]

    def signature(self):
        return struct.unpack_from("<I", self.x, 0x18)[0]

    def code(self):
        out = bytearray()
        for i, p in enumerate(self.pages):
            out += self.x[p:p + min(0x4000, self.codesize - i * 0x4000)]
        return out

    def code_offset(self, ip):
        return self.pages[ip // 0x4000] + ip % 0x4000


def global_ops(code):
    """(address, opcode) of GLOBAL_U16/U24 instructions."""
    from learn_ysc import SIMPLE, U8, S16, U16, JMP, U24
    ip = 0
    while ip < len(code):
        op = code[ip]
        if op in GLOBAL16 | GLOBAL24:
            yield ip, op
        if op in SIMPLE:
            size = 1
        elif op in U8:
            size = 2
        elif op == 38:
            size = 3
        elif op in (39, 44, 93) or op in U24:
            size = 4
        elif op in (40, 41):
            size = 5
        elif op == 45:
            size = 5 + code[ip + 4]
        elif op == 46 or op in S16 or op in U16 or op in JMP:
            size = 3
        elif op == 101:
            size = 2 + 6 * code[ip + 1]
        else:
            size = 1
        ip += size


def convert(s, t):
    """Rewrites `s` in place. Returns (problems, legacy?, guessed globals)."""
    if s.signature() != LEGACY_SIGNATURE:
        return [], False, 0
    problems = []
    guessed = 0
    code = s.code()
    for at, op in global_ops(code):
        g = struct.unpack_from("<H", code, at + 1)[0] if op in GLOBAL16 else code[at + 1] | code[at + 2] << 8 | code[at + 3] << 16
        new, exact = t.global_index(g)
        if new is None:
            problems.append(f"global {g} unknown")
            continue
        if op in GLOBAL16 and new > 0xFFFF:
            problems.append(f"global {g} -> {new} does not fit")
            continue
        guessed += not exact
        for k in range(2 if op in GLOBAL16 else 3):
            s.x[s.code_offset(at + 1 + k)] = (new >> (8 * k)) & 0xFF
    struct.pack_into("<I", s.x, 0x18, ENHANCED_SIGNATURE)
    return problems, True, guessed


def main():
    t = Tables(sys.argv[1])
    if sys.argv[2] == "inc":
        with open(sys.argv[3], "w", encoding="utf-8", newline="\n") as f:
            f.write("// Generated by tools/convert_ysc.py from tools/learn_ysc.py's table (research/phase0.md §26).\n")
            f.write("#ifdef ML_YSC_GLOBALS\n// {legacy global index, Enhanced global index}, sorted\n")
            for a, b in zip(t.legacy, t.enhanced):
                f.write(f"{{{a}, {b}}},\n")
            f.write("#endif\n")
        return
    if sys.argv[2] == "one":
        s = Script(sys.argv[3])
        problems, legacy, guessed = convert(s, t)
        print("legacy" if legacy else "not legacy", len(problems), "problems", problems[:10], guessed, "guessed")
        return
    legacy_dir, enhanced_dir = sys.argv[3:5]
    same = differ = failed = notlegacy = 0
    for name in sorted(set(os.listdir(legacy_dir)) & set(os.listdir(enhanced_dir))):
        try:
            s = Script(os.path.join(legacy_dir, name))
            e = Script(os.path.join(enhanced_dir, name))
        except Exception:
            continue  # not a readable script (a few files in the archives are stubs)
        problems, legacy, guessed = convert(s, t)
        if not legacy:
            notlegacy += 1
        if problems:
            failed += 1
            if failed <= 10:
                print("problems", name, problems[:3])
            continue
        if s.codesize == e.codesize and s.code() == e.code():
            same += 1
        else:
            differ += 1
    print(f"converted == Enhanced: {same}, differ (content changed in the update): {differ}, failed: {failed}, "
          f"no globals signature: {notlegacy}")


if __name__ == "__main__":
    main()
