"""Generate sdk/include/modloader/natives.hpp from the community nativedb (natives.json).
usage: gen_natives.py <natives.json> <out.hpp>"""
import json, sys

KEYWORDS = {"default", "this", "new", "delete", "class", "struct", "template", "operator", "register",
            "unsigned", "char", "float", "int", "bool", "auto", "short", "long", "double", "union",
            "enum", "case", "switch", "return", "public", "private", "protected", "friend", "virtual",
            "namespace", "using", "typename", "const", "static", "volatile", "signed", "void", "for",
            "while", "do", "if", "else", "goto", "break", "continue", "try", "catch", "throw", "inline"}

def ident(name, used):
    name = name if name and (name[0].isalpha() or name[0] == "_") else "_" + (name or "p")
    if name in KEYWORDS:
        name += "_"
    base, i = name, 1
    while name in used:
        i += 1
        name = f"{base}{i}"
    used.add(name)
    return name

db = json.load(open(sys.argv[1], encoding="utf-8"))
out = ["// Generated by tools/gen_natives.py from the community native database (nativedb).",
       "// Hashes are the public ones; the loader translates them for GTA V Enhanced.",
       "#pragma once", '#include "modloader.hpp"', "",
       "using Any = int;", "using BOOL = int;", "using Hash = uint32_t;", "using Vector3 = ml::Vector3;"]
out += [f"using {t} = int;" for t in ("Entity", "Ped", "Vehicle", "Object", "Player", "Cam", "Blip",
                                     "Pickup", "Interior", "ScrHandle", "FireId")]
count = 0
for ns, natives in db.items():
    out += ["", f"namespace {ns}", "{"]
    for h, info in natives.items():
        used = set()
        params = [(p["type"], ident(p["name"], used)) for p in info["params"]]
        sig = ", ".join(f"{t} {n}" for t, n in params)
        args = "".join(f", {n}" for _, n in params)
        ret = info["return_type"]
        out.append(f"\tinline {ret} {info['name']}({sig}) {{ return ml::Invoke<{ret}>({h}ULL{args}); }}")
        count += 1
    out.append("}")
open(sys.argv[2], "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print(f"{count} natives -> {sys.argv[2]}")
