"""learned.json (from learn_ptx.py) -> src/loader/convert/ypt_tables.inc"""
import json
J = json.load(open('learned.json'))
out = ['// Generated by tools/learn_ptx.py from the game\'s legacy and Enhanced particle files (research/phase0.md §23).',
       '// Legacy object type id -> the id the game\'s own Enhanced files use.',
       'constexpr std::pair<uint64_t, uint64_t> kTypeIds[] = {']
for a, b in sorted(J['tmap'].items(), key=lambda kv: int(kv[0], 16)):
    if int(a, 16) != int(b, 16):
        out.append(f'\t{{{a}, {b}}},')
out.append('};')
out.append('')
out.append('// Shader technique -> Enhanced technique index and variable list (hash, type, index, flag, default values +0x20..+0x40).')
out.append('const PtxTechnique kTechniques[] = {')
for key, (entry, n) in sorted(J['tables'].items()):
    shader, tech = key.split('|')
    idx, vars_ = entry
    out.append(f'\t{{"{shader}", "{tech}", {idx}, {{')
    for h, t, i, fl in vars_:
        payload = J['defaults'].get(f'{key}#{hex(h)}', '')
        vals = bytes.fromhex(payload)[:0x20] if t not in (6, 7) else b''
        vals = vals + bytes(0x20 - len(vals))
        out.append(f'\t\t{{{h:#010x}, {t}, {i}, {fl}, {{' + ', '.join(f'{v:#04x}' for v in vals) + '}},')
    out.append('\t}},')
out.append('};')
open(__import__('os').path.join(__import__('os').path.dirname(__file__), '../src/loader/convert/ypt_tables.inc'), 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print(len(J['tmap']), 'type ids,', len(J['tables']), 'techniques')
