"""Learn which audio game data (.rel) entries changed between the legacy game and Enhanced (research/phase0.md §26).
usage: learn_rel.py <Enhanced .rel folder> <out .inc> <legacy .rel folder> [<legacy .rel folder> ...]
(the Enhanced files the game loads, i.e. update.rpf's; legacy folders: every legacy version a mod may start from)

A legacy mod's .rel holds every entry of the file, changed or not. Entries that are the same as in the game are not
applied; entries that equal the legacy game's own version are not applied either (they differ from Enhanced only
because the game was updated). This writes the CRC-32 of the legacy version of every entry that differs between the
two games, keyed by (file type, entry hash), for src/loader/convert/rel_tables.inc.

.rel layout: u32 type, u32 data size, data (u32 stamp, then entries), u32 name table size, name table, u32 entry
count, {u32 hash, u32 offset, u32 size} * count, then tables of u32 offsets into the data. Byte 1-3 of an entry differ
between builds and are ignored."""
import os, struct, sys, zlib


def parse(path):
    d = open(path, "rb").read()
    kind, size = struct.unpack_from("<II", d, 0)
    data = d[8:8 + size]
    p = 8 + size
    names = struct.unpack_from("<I", d, p)[0]
    p += 4 + names
    count = struct.unpack_from("<I", d, p)[0]
    p += 4
    entries = {}
    for i in range(count):
        h, o, n = struct.unpack_from("<III", d, p + 12 * i)
        entries[h] = data[o:o + n]
    return kind, entries


def normal(entry):
    return entry[:1] + b"\0\0\0" + entry[4:] if len(entry) >= 4 else entry


def main():
    enhanced_dir, out = sys.argv[1:3]
    rows = set()
    for legacy_dir in sys.argv[3:]:
        for name in sorted(set(os.listdir(legacy_dir)) & set(os.listdir(enhanced_dir))):
            kind, legacy = parse(os.path.join(legacy_dir, name))
            _, enhanced = parse(os.path.join(enhanced_dir, name))
            changed = 0
            for h in sorted(set(legacy) & set(enhanced)):
                if normal(legacy[h]) != normal(enhanced[h]):
                    rows.add((kind, h, zlib.crc32(normal(legacy[h]))))
                    changed += 1
            print(f"{legacy_dir} {name}: {changed} entries changed", file=sys.stderr)
    with open(out, "w", newline="\n") as f:
        f.write("// Generated by tools/learn_rel.py: CRC-32 of legacy audio game data entries that Enhanced changed.\n")
        f.write("// {file type, entry hash, crc of the legacy entry with bytes 1-3 cleared}\n")
        for kind, h, crc in sorted(rows):
            f.write(f"{{{kind}, 0x{h:08x}, 0x{crc:08x}}},\n")
    print(len(rows), "rows")


if __name__ == "__main__":
    main()
